services:
  db:
    image: postgres:16-alpine
    container_name: petshop-postgres-db
    restart: always
    environment:
      POSTGRES_DB: petshop-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5332:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data